name: Run Unit Tests

on:
    push:
        branches:
        - 'disabled-master'
        - 'disabled-develop'
        - 'disabled-feature/**'
        - 'disabled-release/**'
        - 'disabled-bugfix/**'
        - 'disabled-hotfix/**'

env:
  TERM: xterm

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: install modules
          run: npm install
        - name: test module
          run: npm run test:ci
